FROM node:lts-alpine
WORKDIR /app
RUN apk --no-cache add curl
COPY package*.json ./
COPY tsconfig*.json ./
COPY codegen.ts ./
RUN touch /usr/local/bin/husky && chmod +x /usr/local/bin/husky 
RUN npm install
COPY public public
COPY src src
COPY index.html ./
# COPY components.json ./
COPY *.config.ts ./
COPY *.config.js ./

CMD ["npm", "run", "dev"]