FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
RUN npm install
RUN npm install -g typescript
COPY src src
RUN tsc --outDir /app/dist

FROM node:lts-alpine
RUN apk --no-cache add curl
WORKDIR /app
COPY --from=builder /app/dist .
COPY --from=builder /app/package.json .
RUN npm install --production
CMD ["npm", "run start"]
