FROM mcr.microsoft.com/playwright:v1.55.0-jammy
WORKDIR /app
COPY package.json .
COPY playwright.config.ts .
RUN touch /usr/local/bin/husky && chmod +x /usr/local/bin/husky 
RUN npm install
COPY tests/ ./tests/
CMD npx playwright test
