FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
RUN touch /usr/local/bin/husky && chmod +x /usr/local/bin/husky 
RUN npm i
RUN npm i -g typescript
COPY src/ .
RUN tsc

# faire un container "propre" + copier le build dedans
FROM node:lts-alpine 
WORKDIR /app
COPY --from=builder /app/build ./build
COPY package*.json .
RUN touch /usr/local/bin/husky && chmod +x /usr/local/bin/husky 
RUN npm i --production
CMD ["npm", "run", "start"]