name: Hello W0rld

on:
  pull_request:
    branches:
      - dev
    types: [opened, reopened, synchronize]

jobs:
  tell-node-version:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Node version plz
        run: node -v

  say-hi:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hi
        run: echo "Hello world"
